"""add user identities migrate to zitadel auth

Revision ID: 70aa69110e7a
Revises: b785e4b63db7
Create Date: 2026-04-18 11:30:06.066044

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "70aa69110e7a"
down_revision: str | Sequence[str] | None = "b785e4b63db7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _drop_fk(table: str, column: str) -> None:
    conn = op.get_bind()
    result = conn.execute(
        sa.text("""
        SELECT CONSTRAINT_NAME
        FROM information_schema.KEY_COLUMN_USAGE
        WHERE TABLE_NAME = :table
          AND TABLE_SCHEMA = DATABASE()
          AND COLUMN_NAME = :column
          AND REFERENCED_TABLE_NAME IS NOT NULL
    """),
        {"table": table, "column": column},
    )
    for row in result.fetchall():
        op.drop_constraint(row[0], table, type_="foreignkey")


def upgrade() -> None:
    # 1. Drop refresh_tokens — FK name is unpredictable (pre-convention)
    _drop_fk("refresh_tokens", "user_id")
    op.drop_index("ix_refresh_tokens_user_id", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")

    # 2. Drop password_hash
    op.drop_column("users", "password_hash")

    # 3. Replace auto-named unique index on submission_records
    op.drop_index("assessment_id", table_name="submission_records")
    op.create_unique_constraint(
        op.f("uq_submission_records_assessment_id"),
        "submission_records",
        ["assessment_id", "student_id"],
    )

    # 4. Replace auto-named unique index on submission_results
    op.drop_index("submission_id", table_name="submission_results")
    op.create_unique_constraint(
        op.f("uq_submission_results_submission_id"),
        "submission_results",
        ["submission_id", "question_id"],
    )

    # 5. Create user_identities
    op.create_table(
        "user_identities",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("provider_user_id", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_identities_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_identities")),
        sa.UniqueConstraint("provider", "provider_user_id", name="uq_provider_user"),
    )
    op.create_index(
        op.f("ix_user_identities_user_id"), "user_identities", ["user_id"], unique=False
    )


def downgrade() -> None:
    # 1. Drop user_identities — FK name is known (post-convention)
    op.drop_constraint(
        op.f("fk_user_identities_user_id_users"), "user_identities", type_="foreignkey"
    )
    op.drop_index(op.f("ix_user_identities_user_id"), table_name="user_identities")
    op.drop_table("user_identities")

    # 2. Restore auto-named unique index on submission_results
    op.drop_constraint(
        op.f("uq_submission_results_submission_id"), "submission_results", type_="unique"
    )
    op.create_index(
        "submission_id", "submission_results", ["submission_id", "question_id"], unique=True
    )

    # 3. Restore auto-named unique index on submission_records
    op.drop_constraint(
        op.f("uq_submission_records_assessment_id"), "submission_records", type_="unique"
    )
    op.create_index(
        "assessment_id", "submission_records", ["assessment_id", "student_id"], unique=True
    )

    # 4. Restore password_hash
    op.add_column("users", sa.Column("password_hash", sa.String(length=255), nullable=False))

    # 5. Restore refresh_tokens — new table, FK name will be auto-generated by MariaDB
    op.create_table(
        "refresh_tokens",
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("current_timestamp()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("jti"),
    )
    op.create_index("ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"], unique=False)
