"""update assessment source_data text length

Revision ID: 7ee662ca49af
Revises: 10444def0dc4
Create Date: 2026-04-03 12:05:05.057638

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "7ee662ca49af"
down_revision: str | Sequence[str] | None = "10444def0dc4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assessments",
        "source_data",
        existing_type=mysql.TEXT(),
        type_=sa.Text()
        .with_variant(mysql.MEDIUMTEXT(), "mariadb")
        .with_variant(mysql.MEDIUMTEXT(), "mysql"),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assessments",
        "source_data",
        existing_type=sa.Text()
        .with_variant(mysql.MEDIUMTEXT(), "mariadb")
        .with_variant(mysql.MEDIUMTEXT(), "mysql"),
        type_=mysql.TEXT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
