"""assessment finegrained updated at

Revision ID: b785e4b63db7
Revises: 7ee662ca49af
Create Date: 2026-04-05 13:24:09.906422

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b785e4b63db7"
down_revision: str | Sequence[str] | None = "7ee662ca49af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assessments", sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "assessments",
        sa.Column("question_set_updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "assessments", sa.Column("rubric_updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "assessments", sa.Column("results_updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assessments", "results_updated_at")
    op.drop_column("assessments", "rubric_updated_at")
    op.drop_column("assessments", "question_set_updated_at")
    op.drop_column("assessments", "source_updated_at")
    # ### end Alembic commands ###
